### ISSUE TITLE
The template parameter example isn't working

### ISSUE THREAD

**Issue by crivetechie** [PagerDuty/backstage-plugin-backend#12]
**Describe the bug**

The example provided in https://pagerduty.github.io/backstage-plugin-docs/advanced/create-service-software-template/ doesn't work even after having followed the provided instructions to setup the plugin: the `escalation_policy_id` displays an error.

When using the suggested configuration

```yaml
        escalation_policy_id:
          title: Escalation Policy ID
          type: string
          description: The ID of the escalation policy to associate with the service
          ui:field: SelectFieldFromApi 
          ui:options: 
            title: PagerDuty Escalation Policy
            description: Select an escalation policy from PagerDuty
            path: 'pagerduty/escalation_policies' 
            labelSelector: 'label'
            valueSelector: 'value'
            placeholder: '---'
```

The software template invokes the endpoint `<backstagehost>/pagerduty/escalation_policies` which returns a `404` and therefore prevent the field from rendering the escalation policies.

I tried to update the configuration to use the proxy path instead and the policies gets listed but it requires setting `arraySelector` option and changing `labelSelector` and `valueSelector`, working config:

```yaml
    - title: PagerDuty
      properties:
        escalation_policy_id:
          title: Escalation Policy ID
          type: string
          description: The ID of the escalation policy to associate with the service
          ui:field: SelectFieldFromApi 
          ui:options: 
            title: PagerDuty Escalation Policy
            description: Select an escalation policy from PagerDuty
            path: 'proxy/pagerduty/escalation_policies' 
            labelSelector: 'name'
            valueSelector: 'id'
            placeholder: '---'
            arraySelector: 'escalation_policies'
```

The pagerduty configuration in app-config for Backstage is as follow:

```yaml
proxy:
  '/pagerduty':
    target: https://api.pagerduty.com
    headers:
      Authorization: Token token=${PAGERDUTY_TOKEN}
    allowedMethods: ['GET']

pagerDuty:
  apiToken: ${PAGERDUTY_TOKEN}
```
